// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ckepjvscfdcthjxsiebj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNrZXBqdnNjZmRjdGhqeHNpZWJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2MDg0MTEsImV4cCI6MjA3NDE4NDQxMX0.ZOCCmq5xpR7lJcZPiJat1o-Czs2qq5UJlmW_hzZ2Uzg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});